### ISSUE TITLE
Не устанавливается на Firefox

### ISSUE THREAD

**Issue by medwuu** [ItsEthra/MireaJacked#2]
Делаю всё по инструкции, но расширение на Firefox не ставится. Вылезает ошибка. Может быть что-то с манфестом? ¯\_(ツ)_/¯
![proof](https://github.com/ItsEthra/MireaJacked/assets/91782808/6f3806f5-848b-4392-a2db-7c8f4cce2e69)

**Comment by ItsEthra** [comment]
Необходимо загружать как temporarily extension так как этот аддон не подписан, можно попробовать по этой ссылке `about:debugging#/runtime/this-firefox`
![image](https://github.com/ItsEthra/MireaJacked/assets/107059409/e84f4abc-7831-4ba7-b7af-cdb4f5756787)

**Comment by medwuu** [comment]
Да. Вот так работает ✌🏻
